### ISSUE TITLE
Iteration plan for August 2017

### ISSUE THREAD

**Issue by sethstha** [themegrill/suffice#6]
## Overview
Iteration for August 2017

## Endgame
- _August 29th_: Code freeze for the end game
- _September 1st_: End game done

### Customizer
- [x] Fix - Customizer option for menu is not working when primary menu is not set #8 @ashishsthanp 
- [x] Fix - Sticky header sliding completely upwards when header is center and menu is set to offcanvas #9  @ashishsthanp 

### Debug
- [x] As `get_theme_mod` is changed to `suffice_get_option` many settings are being effected. Test the settings @mebishalnapit 
- [x] Sticky header settings not working on customizer but works on front-end #10 @sethstha

### Code
- [x] Moderate theme to meet new WordPress Coding Standards 0.13.1 #1 @ashishsthanp 

### Theme
- [x] Fix - sub menu is way too downwards and not able to hover #15 @sethstha
- [x] Add - Close icon on offcanvas menu #16 @ashishsthanp 
- [x] Destroy sticky header on mobile device #14  @ashishsthanp @sethstha

### UX
- [x] Add icon on customizer option #13  @lprabha @sethstha
